spring:
  application:
    name: microservice-reservation

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Añadir configuración de Feign
feign:
  client:
    config:
      user-service:
        url: http://user-service:8080
        connectTimeout: 5000
        readTimeout: 5000
      court-service:
        url: http://court-service:8080
      club-service:
        url: http://club-service:8080

jwt:
  secret: ${JWT_SECRET:defaultUnsecureKeyForDevelopmentOnlyChangeInProduction}
  token-validity-in-seconds: ${JWT_TOKEN_VALIDITY:86400}

server:
  port: ${SERVER_PORT:8082}

springdoc:
  api-docs:
    path: /api
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.example.microserviceuser: INFO
    org.springframework.security: DEBUG
    # Añadir logging para Feign
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG