spring:
  application:
    name: microservice-notification
    profiles:
      active: ${SPRING_PROFILES_ACTIVE:local}
      datasource:
        driver-class-name: org.postgresql.Driver
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:password}
        url: ${DB_URL:jdbc:postgresql://localhost:5432/reservas_db}
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true

jwt:
  secret: ${JWT_SECRET:defaultUnsecureKeyForDevelopmentOnlyChangeInProduction}
  token-validity-in-seconds: ${JWT_TOKEN_VALIDITY:86400}

server:
  port: ${SERVER_PORT:8084}

springdoc:
  api-docs:
    path: /api
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.example.microserviceuser: INFO
    org.springframework.security: DEBUG